### ISSUE TITLE
TypeError: Can't instantiate abstract class Datasets with abstract methods _get_dataset_path_internal, _log, refresh

### ISSUE THREAD

**Issue by tangxitao** [TimeEval/TimeEval-algorithms#51]
When running TimeEval/notebooks/data-prep/Server Machine Dataset.ipynb，how to solve it ?
![image](https://github.com/user-attachments/assets/94ac50ae-4872-46b5-93a8-ddecaff34ef9)

**Comment by CodeLionX** [comment]
The notebooks, unfortunately, still use old versions of TimeEval. Thus, this code does not run out-of-the-box.

---

Please use the [`timeeval.datasets.DatasetManager`](https://timeeval.readthedocs.io/en/latest/api/timeeval.datasets.html#timeeval.datasets.dataset_manager.DatasetManager) instead of the abstract `Datasets`-class.

**Comment by CodeLionX** [comment]
I assume the issue is solved and close it. If you still have problems with the code, please open a new issue.
