### ISSUE TITLE
Issue with building or pulling images - Registry.gitlab.hpi.de

### ISSUE THREAD

**Issue by kalifou** [TimeEval/TimeEval-algorithms#54]
Hello,

I am currently trying to run a benchmark using a project derived from your code (ESA/TimeEval-Algorithm ), for specialized data.

When migrating the code to a larger machine (more ressources but with a same setup), I now have the following issues building the algorithm images on the second machine. 

In particular, the error that arises is generated by the metadata for your registry (registry.gitlab.hpi.de/akita/i/pyod-1.1.2)

Question: In your opinion, what could cause such issue 403?

Thanks a lot.
Cheers

```
Machine$ docker build -t registry.gitlab.hpi.de/akita/i/copod ./copod
[+] Building 1.4s (3/3) FINISHED                                                                                                                                                                                                  
 => [internal] load build definition from Dockerfile                                                                                                                                                                        
 => => transferring dockerfile: 295B                                                                                                                                                                                        
 => [internal] load .dockerignore                                                                                                                                                                                          
 => => transferring context: 2B                                                                                                                                                                                             
 => ERROR [internal] load metadata for registry.gitlab.hpi.de/akita/i/pyod-1.1.2:latest                                                                                                                                     
------
 > [internal] load metadata for registry.gitlab.hpi.de/akita/i/pyod-1.1.2:latest:
------
Dockerfile:1
--------------------
   1 | >>> FROM registry.gitlab.hpi.de/akita/i/pyod-1.1.2
   2 |     
   3 |     LABEL maintainer="sebastian.schmidl@hpi.de"
--------------------
ERROR: failed to solve: registry.gitlab.hpi.de/akita/i/pyod-1.1.2: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

**Comment by CodeLionX** [comment]
Dear René,
unfortunately, [ESA-ADB](https://github.com/kplabs-pl/ESA-ADB), which I suppose you are referring to, uses an old copy of the TimeEval code and algorithms. We moved all our algorithms to the GitHub registry. Please consider using the algorithms from https://github.com/timeeval/timeeval-algorithms directly — there is no need to build the algorithms yourself anymore.

E.g., you can use the image [`ghcr.io/timeeval/copod:0.4.0`](https://github.com/TimeEval/TimeEval-algorithms/pkgs/container/copod) for COPOD without the need to build the images yourself.

If you cannot use our pre-published algorithm images, please follow this guide to build the algorithms yourself: https://timeeval.readthedocs.io/en/latest/user/usage-timeeval.html#prepare-algorithms

---

The HPI GitLab registry (registry.gitlab.hpi.de) can only be used by HPI employees and students. You would need an account for it. Because you are not authenticated, you get the 403 (Unauthorized).

**Comment by kalifou** [comment]
Dear Sebastian,

Thanks for such a prompt reply!
Got you,I will then follow your recommendations.

I also managed to get around the issue by replacing the base image import (FROM registry.gitlab.hpi.../pyod with ghcr.io.../pyod)
This fixes my current errrors and completes my tests, which are important, given that I need to reproduce some experiments with the ESA-ABD as is.

Thank you
Cheers.
